package com.tacplatform.transaction.smart.script.estimator

import com.tacplatform.lang.v1.estimator.ScriptEstimatorV1

class ContractScriptComplexityV1Test extends ContractScriptComplexityTest(ScriptEstimatorV1)